import Head from "next/head";
import styles from "@/styles/Home.module.css";
import BlogCard from "@/components/BlogCard/BlogCard";
import { GetStaticProps } from "next";
import Navbar from "@/components/Navbar/Navbar";
import { AllPosts, Post } from "@/utils/types/types";
import { ALL_POSTS_QUERY } from "@/utils/queries/postsQuery";
import { graphcms } from "@/utils/client/graphqlClient";
import { pages } from "@/utils/pages";

export const getStaticProps: GetStaticProps<AllPosts> = async () => {
  const { posts } = await graphcms.request<{ posts: Post[] }>(ALL_POSTS_QUERY);
  return {
    props: {
      posts: posts.reverse(),
    },
    revalidate: 10,
  };
};

export default function Home({ posts }: AllPosts) {
  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <>
          <Navbar pages={pages} />
          <div className={styles.posts}>
            {posts.map((post, index) => {
              return (
                <BlogCard
                  title={post.title}
                  author={post.author.name}
                  authorPic={post.author.avatar.url}
                  category={post.category}
                  datePublished={post.datePublished}
                  coverPhoto={post.coverPhoto.url}
                  slug={post.slug}
                  excerpt={post.excerpt}
                  key={index}
                />
              );
            })}
          </div>
        </>
      </main>
    </>
  );
}
